apiVersion: v1
kind: Pod
metadata:
  name: devopspod
  labels:
    name: devopspod
spec:
  containers:
    - name: devopspod
      image: msantinello/conversao-temperatura:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: devopspodgreen
  labels:
    app: green
spec:
  containers:
    - name: devopspod
      image: msantinello/conversao-temperatura:v2
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
